from typing import Dict, Any, List
from app.services.forecaster import FinancialForecaster
from app.services.optimizer import SavingsOptimizer
from app.models.domain import Transaction, SavingsGoal

class FinancialCopilotService:
    """Tool-using AI Financial Copilot engine that synthesizes answers with actual calculation evidence."""

    @staticmethod
    def answer_user_query(
        query: str,
        user_id: str,
        transactions: List[Transaction],
        goals: List[SavingsGoal]
    ) -> Dict[str, Any]:
        q_lower = query.lower()

        income = sum(t.amount for t in transactions if t.txn_type == "credit")
        expense = sum(t.amount for t in transactions if t.txn_type == "debit")
        current_balance = income - expense if transactions else 25000.0

        forecast = FinancialForecaster.forecast_cashflow(
            transactions=transactions,
            user_id=user_id,
            horizon_days=90,
            initial_balance=current_balance
        )
        
        goal_opt = SavingsOptimizer.optimize_goal_allocations(
            goals=goals,
            user_id=user_id,
            transactions=transactions
        )

        answer = ""
        evidence_data = {}

        if "afford" in q_lower or "expense" in q_lower or "buy" in q_lower:
            # Check upcoming buffer breaches
            if forecast.breaches:
                earliest = forecast.breaches[0]
                answer = (
                    f"Based on your projected 90-day cash flow, adding a large expense is risky right now. "
                    f"Your balance is projected to breach your safety buffer on {earliest.date} with a deficit of ₹{earliest.shortfall:,.2f}."
                )
            else:
                answer = (
                    f"Yes! Your cash flow is healthy with no projected buffer breaches over the next 90 days. "
                    f"Your projected balance at end of horizon is ₹{forecast.end_balance:,.2f}."
                )
            evidence_data = {
                "projected_end_balance": forecast.end_balance,
                "buffer_breaches_count": len(forecast.breaches),
                "safe_buffer_limit": forecast.safe_buffer
            }

        elif "why" in q_lower or "buffer" in q_lower or "fall" in q_lower:
            if forecast.breaches:
                b = forecast.breaches[0]
                answer = (
                    f"Your balance drops below your ₹{b.safe_buffer:,.2f} safety buffer on {b.date} primarily due to: "
                    f"{', '.join(b.primary_causes)}."
                )
            else:
                answer = f"Your projected balance remains safely above your ₹{forecast.safe_buffer:,.2f} buffer across the next 90 days."
            evidence_data = {"causes": forecast.breaches[0].primary_causes if forecast.breaches else ["Steady cash flow"]}

        elif "goal" in q_lower or "save" in q_lower:
            if goal_opt.conflicts_detected:
                answer = f"Goal conflicts detected: {goal_opt.conflicts_detected[0]}"
            else:
                answer = f"Your monthly available surplus of ₹{goal_opt.monthly_available_surplus:,.2f} is sufficient to fund all active savings goals!"
            evidence_data = {"monthly_surplus": goal_opt.monthly_available_surplus, "allocations_count": len(goal_opt.allocations)}

        else:
            answer = (
                f"Hello! I am your BrokeNoMore Financial Copilot. Your current estimated net balance is ₹{current_balance:,.2f}. "
                f"Your 90-day forecast ends at ₹{forecast.end_balance:,.2f} with {len(forecast.breaches)} projected buffer breaches."
            )
            evidence_data = {"current_balance": current_balance, "end_balance": forecast.end_balance}

        return {
            "query": query,
            "answer": answer,
            "evidence": evidence_data,
            "disclaimer": (
                "This response was generated by a rule-based keyword router, NOT an LLM. "
                "Financial figures are derived directly from your transaction history via: "
                "historical run-rate cash-flow forecasting (FinancialForecaster) and, when goals "
                "are queried, SciPy HiGHS linear programming (SavingsOptimizer). "
                "No AI language model, no external API, and no invented numbers are used."
            )
        }
